ecommerce:
  outputs:
    prod:
      type: postgres
      host: postgresql-service.ecommerce-pipeline.svc.cluster.local
      port: 5432
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('POSTGRES_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_DB') }}"
      schema: analytics
      threads: 2
  target: prod